### PR TITLE
fix parsing issue &

### PR DESCRIPTION
**Pull request by ken0x0a**
- 123***789 => should be parsed as string ( fix: crash )
- aiu [ true, false ] => should be string ( fix: parsed as list (`[true,false]`) )
- 09123112 => should be string in Yaml 1.2 ? ( fix: parsed as i64 )
- `e: 1` => key should be `e` ( fix: parsed as `0` in ab648c548d59fc9521e083a846daa4c1d9bf3dd1 )
- `1-2` => should be string ( fix: parsed as int `1` in c6d59e595c3edc3caa3923c653445c912af43535 )

## Note

I think this ( aff874b8db6bee656970b83ca70557a54917d458 ) commit is doing something wrong.
But I couldn't fix parsing issue for following non indent array syntax without it (required so many changes otherwise).

```yaml
array:
- 1
- 2
- 3
```

## Non bug fix change

- `null` support (not necessary for Vlang though, useful when converting format ) cca7a4ac5b5f29a8004adbcd83dd523d7accd9b9
- Yaml 1.1 octal parsing with build option `-d yaml_1_1_octal` cd6c7173cbc04829d915eea767dbc4dd373ab5ae

### CODE REVIEW

**Comment by jdonnerstag** [comment]
Thanks a lot. I only reverted the write_byte() change. I updated v to the latest commit, but write_byte is not yet included. May be it is in your dev branch only?

**Comment by ken0x0a** [comment]
Thank you for merging this!!

`write_byte` is merged to V REPO in 8 days ago https://github.com/vlang/v/pull/13313 .
I guess, you might try to fix some V's bug in V src dir, and `v up` is not working properly.
Or, sometime, there might have intermediate files...

So, the following might resolve that issue
```sh
git clean -dfx # good to check by `git clean -ndfx` before
make
```

**Comment by jdonnerstag** [comment]
`v up`  is not working on Win10. I usually do `make.bat -tcc` instead, which as you can see also updates the source code.

```
C:\source_code\vlang\v>git clean -dfx
Removing cmd/tools/vdoctor.exe
Removing cmd/tools/vself.exe
Removing cmd/tools/vtest.exe
Removing v.def
Removing v.exe
Removing v2.def
Removing v_old.exe

C:\source_code\vlang\v>make.bat -tcc
Updating TCC
 > Syncing TCC from https://github.com/vlang/tccbin

Updating vc...
 > Sync with remote https://github.com/vlang/vc

Building V...
 > Attempting to build v_win.c with TCC
 > Compiling with .\v.exe self
V self compiling (-keepc -g -showcc -cc C:\source_code\vlang\v\thirdparty\tcc\tcc.exe -o v2)...
> C compiler cmd: "C:\source_code\vlang\v\thirdparty\tcc\tcc.exe" "@C:\Users\jdonnerstag\AppData\Local\Temp\v_0\v2.tmp.c.rsp"
> C compiler response file "C:\Users\jdonnerstag\AppData\Local\Temp\v_0\v2.tmp.c.rsp":
  -std=c99 -D_DEFAULT_SOURCE -g -o "C:\\source_code\\vlang\\v\\v2.exe" -I "C:\\source_code\\vlang\\v\\thirdparty\\stdatomic\\win" "C:\\Users\\jdonnerstag\\AppData\\Local\\Temp\\v_0\\v2.tmp.c" -municode -bt25 -ldbghelp -ladvapi32 -lshell32
V built successfully!
 > V built successfully
 > To add V to your PATH, run `.\v.exe symlink`.

V version: V 0.2.4 66a67de
```

To be on the safe site, I removed the .\v directory and re-installed V from scratch. And in fact, it reports another commit `V version: V 0.2.4 66f21ca`. Interesting. And this now also works with write_byte.

**Comment by ken0x0a** [comment]
I'm on macOS, but I actually, also, had an issue like that before 😭
Thank you for trying anyway.

**Pull request merged**
